# Generated by Django 4.2.13 on 2024-06-27 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appMesaServicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casCodigo', models.CharField(db_comment='codigo unico del caso', max_length=10, unique=True)),
                ('casEstado', models.CharField(choices=[('Solicitada', 'Solicitada'), ('En proceso', 'En proceso'), ('Finalizada', 'Finalizada')], default='Solicitada', max_length=20)),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='fecha y hora de ultima actualización de la solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='SolucionCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solProcedimiento', models.TextField(db_comment='Texto del procedimiento realizado en la solución del caso', max_length=2000)),
                ('solTipoSolucion', models.CharField(choices=[('Parcial', 'Parcial'), ('Definitiva', 'Definitiva')], db_comment='Tipo de la solucuín, si es parcial o definitiva', max_length=20)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora de creacion')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora de actualizacion')),
                ('solCaso', models.ForeignKey(db_comment='hace ref a la solicitud que genero el caso', on_delete=django.db.models.deletion.PROTECT, to='appMesaServicio.caso')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipNombre', models.CharField(db_comment='tipo de procedimiento', max_length=30, unique=True)),
                ('tipDescripcion', models.TextField(db_comment='texto con la descripcion del procedimiento', max_length=1000)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='fecha y hora de ultima actualización de la solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='SolucionCasotipoProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solSolucionCaso', models.ForeignKey(db_comment='Llave foranea de Solucion del caso', on_delete=django.db.models.deletion.PROTECT, to='appMesaServicio.solucioncaso')),
                ('solTipoProcedimiento', models.ForeignKey(db_comment='Llave foranea de Solucion de Tipo de procedimiento', on_delete=django.db.models.deletion.PROTECT, to='appMesaServicio.tipoprocedimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solDescripcion', models.TextField(db_comment='descripción solicitud del empleado', max_length=1000)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='fecha y hora del registro de solicitud')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='fecha y hora de ultima actualización de la solicitud')),
                ('solOficinaAmbiente', models.ForeignKey(db_comment='hace ref a la oficina o ambiente donde se requiere la solicitud', on_delete=django.db.models.deletion.PROTECT, to='appMesaServicio.oficinaambiente')),
                ('solUsuario', models.ForeignKey(db_comment='hace ref al empleado que hace la solicitud', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='caso',
            name='casSolicitud',
            field=models.ForeignKey(db_comment='hace ref a la solicitud que genero el caso', on_delete=django.db.models.deletion.PROTECT, to='appMesaServicio.solicitud'),
        ),
        migrations.AddField(
            model_name='caso',
            name='casUsuario',
            field=models.ForeignKey(db_comment='Empleado de soporte técnico asignado al caso', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
